<!-- 
用ipython notebook
用numpy，包括函数调用及向量矩阵运算
理解“广播”的概念
向量化代码 
-->

In [1]:
### START CODE HERE ### (≈ 1 line of code)
test = "Hello World"
### END CODE HERE ###
print ("test: " + test)

test: Hello World


#学习一些关键的numpy函数，例如np.exp，np.log和np.reshape

# 1.1- sigmoid function和np.exp（）

In [6]:
import math
def sigmoid(x):
    #float x,sigmoid_x
    sigmoid_x = 1/(1+math.exp(-x))
    return sigmoid_x
sigmoid(3)

0.9525741268224334

In [11]:
### One reason why we use "numpy" instead of "math" in Deep Learning ###
# x = [1, 2, 3]
# sigmoid(x) # you will see this give an error when you run it, because x is a vector.

np.exp就不同，可以计算矢量vector,可以依次计算exp（x）

In [9]:
import numpy as np

# example of np.exp
x = np.array([1, 2, 3])
print(np.exp(x)) # result is (exp(1), exp(2), exp(3))

[ 2.71828183  7.3890561  20.08553692]


In [10]:
import numpy as np
def sigmoid_np(x):
    #float x,sigmoid_x
    sigmoid_x = 1/(1+np.exp(-x))
    return sigmoid_x
x = np.array([1, 2, 3])
sigmoid_np(x)

array([0.73105858, 0.88079708, 0.95257413])

# 1.2- Sigmoid gradient

In [12]:
def sigmoid_gradient(x):              #sigmoid derivative
    #float x,sigmoid_x
    sigmoid_x = 1/(1+np.exp(-x))
    dsigmoid_x = sigmoid_x*(1-sigmoid_x)
    return dsigmoid_x
x = np.array([1, 2, 3])
print ("sigmoid_derivative(x) = " + str(sigmoid_gradient(x)))

sigmoid_derivative(x) = [0.19661193 0.10499359 0.04517666]


# 1.3- 重塑数组

深度学习中两个常用的numpy函数是np.shape和np.reshape()。
-X.shape用于获取矩阵/向量X的shape（维度）
-X.reshape（...）用于将X重塑为其他尺寸

练习：实现image2vector() ,该输入采用维度为(length, height, 3)的输入，并返回维度为(length*height*3, 1)的向量。
例如，如果你想将形为（a，b，c）的数组v重塑为维度为(a*b, 3)的向量，则可以执行以下操作：

v = v.reshape((v.shape[0]*v.shape[1], v.shape[2])) # v.shape[0] = a ; v.shape[1] = b ; v.shape[2] = c
-请不要将图像的尺寸硬编码为常数。而是通过image.shape [0]等来查找所需的数量。

In [19]:
# GRADED FUNCTION: image2vector
def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape (length, height, depth)
    
    Returns:
    v -- a vector of shape (length*height*depth, 1)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    v = image.reshape(image.shape[0] * image.shape[1] * image.shape[2], 1)
    ### END CODE HERE ###
    
    return v
# This is a 3 by 3 by 2 array, typically images will be (num_px_x, num_px_y,3) where 3 represents the RGB values
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])
print(image.shape)
print ("image2vector(image) = " + str(image2vector(image)))

(3, 3, 2)
image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


# 1.4- 行标准化

由于归一化后梯度下降的收敛速度更快，通常会表现出更好的效果。 通过归一化，也就是将x更改为:将x的每个行向量除以其范数

In [20]:
# GRADED FUNCTION: normalizeRows

def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    
    ### START CODE HERE ### (≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
    x_norm = np.linalg.norm(x, axis = 1, keepdims = True)
    
    # Divide x by its norm.
    x = x / x_norm
    ### END CODE HERE ###

    return x
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


# 1.5- 广播和softmax函数

这对于在不同形状的数组之间执行数学运算非常有用

In [21]:
def softmax(x):
    """Calculates the softmax for each row of the input x.

    Your code should work for a row vector and also for matrices of shape (n, m).

    Argument:
    x -- A numpy matrix of shape (n,m)

    Returns:
    s -- A numpy matrix equal to the softmax of x, of shape (n,m)
    """
    
    ### START CODE HERE ### (≈ 3 lines of code)
    # Apply exp() element-wise to x. Use np.exp(...).
    s1 = np.exp(x)
    s2 = np.sum(s1,axis=1,keepdims=True)
    softmax_x=s1/s2
    return softmax_x
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(x)))

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


# 2.实现L1和L2损失函数

In [23]:
# GRADED FUNCTION: L1

def L1(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L1 loss function defined above
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    loss = np.sum(np.abs(y - yhat))
    ### END CODE HERE ###
    
    return loss
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


In [26]:
# GRADED FUNCTION: L2

def L2(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L2 loss function defined above
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    loss = np.dot((y - yhat),(y - yhat).T)
#     loss=np.sum(np.multiply((y-yhat),(y-yhat)))
    ### END CODE HERE ###
    
    return loss
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = 0.43


主要是机器学习中的最基本的编程知识，参考:
https://www.heywhale.com/mw/project/5dd236a800b0b900365eca9b
numpy数组向量化，以及numpy数组常用的函数，
矩阵一整行求和，
矩阵一整行求2范数（算术平方和），
不同型的矩阵广播机制
sigmoid函数及其导数，
L1范数与L2范数